Additions to test_netstats and removal of redundancy in netstats
dPys/PyNets pull request #470
Opened 2021-01-06 04:58 UTC by alexayala08

Added tests for get_prop_type() and nx2gt().

Removed redundant code in pynets/stats/netstats

2021-01-06 05:14 UTC, dPys requested changes
@alexayala08 -- nice work on this. Just a couple comments/suggestions to address before we go ahead and merge. Before doing anything new though, go ahead and run `git fetch upstream` and `git merge origin/development` since I've merged some changes from earlier that are not yet synced with the dev branch on your fork.

2021-01-06 05:14 UTC, dPys commented on tests/test_netstats.py
> +    assert tname is not None
Can form more meaningful assert statement here given that we know tname will have to take on one of either: 
'bool', 'float', 'string', 'object'.

2021-01-06 05:14 UTC, dPys commented on tests/test_netstats.py
> +    assert gtG is not None
Here too, we should expand upon this assert. One thing to consider is that if nxG is not None (i.e. and it's a true nx.Graph versus, say, a np.ndarray), then gtG should always return a valid graph_tool graph object.

2021-01-12 06:43 UTC, alexayala08 commented
The failed tests seem to because I am importing graph_tool. Should I import graph_tool in the individual test functions similar to how it is done in tests/netstats where it is inside of a try and except statement?

2021-01-13 16:16 UTC, dPys commented
> The failed tests seem to because I am importing graph_tool. Should I import graph_tool in the individual test functions similar to how it is done in tests/netstats where it is inside of a try and except statement?

Yes! That's exactly the way to do it :-)

2021-02-14 18:42 UTC, dPys approved these changes

2021-02-14 22:26 UTC, dPys commented
Merging with development! :-)

2021-02-14 22:26 UTC, merged